### ISSUE TITLE
GridViewTVbug

### ISSUE THREAD

**Issue by darrennight** [FrozenFreeFall/Android-tv-widget#9]
向下移动如果当前列的下一行没有数据是出现此问题

FATAL EXCEPTION: main
                                                               Process: com.open.demo, PID: 22260
                                                               java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
                                                                   at android.view.ViewGroup.canViewReceivePointerEvents(ViewGroup.java:2316)
                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1581)
                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2377)
                                                                   at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1729)
                                                                   at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2778)
                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2344)
                                                                   at android.view.View.dispatchPointerEvent(View.java:8668)
                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
                                                                   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
                                                                   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
                                                                   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
                                                                   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                   at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                   at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                   at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5868)
                                                                   at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5920)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.ja

**Comment by FrozenFreeFall** [comment]
那你就不要用gridviewtv了，谢谢.
或者自己查出问题，先注释吧

hailong.qiu@xgimi.com

From: Darren
Date: 2016-06-04 15:53
To: FrozenFreeFall/Android-tv-widget
Subject: [FrozenFreeFall/Android-tv-widget] GridViewTVbug (#9)
向下移动如果当前列的下一行没有数据是出现此问题
FATAL EXCEPTION: main
Process: com.open.demo, PID: 22260
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
at android.view.ViewGroup.canViewReceivePointerEvents(ViewGroup.java:2316)
at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1581)
at android.view.View.dispatchGenericMotionEvent(View.java:8552)
at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
at android.view.View.dispatchGenericMotionEvent(View.java:8552)
at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
at android.view.View.dispatchGenericMotionEvent(View.java:8552)
at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
at android.view.View.dispatchGenericMotionEvent(View.java:8552)
at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
at android.view.View.dispatchGenericMotionEvent(View.java:8552)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2377)
at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1729)
at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2778)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2344)
at android.view.View.dispatchPointerEvent(View.java:8668)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5868)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5920)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:548)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5257)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.ja
